# Generated by Django 5.1 on 2024-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment')], max_length=20)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
