# Generated by Django 5.1 on 2024-09-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
