# Generated by Django 5.1 on 2024-09-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_markerinteraction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markerinteraction',
            unique_together=set(),
        ),
    ]
