# Generated by Django 5.1 on 2024-10-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('max_invites', models.IntegerField(default=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_start_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.user')),
            ],
        ),
    ]
