# Generated by Django 5.1.2 on 2024-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_projectsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='users',
            field=models.ManyToManyField(null=True, related_name='projects', to='api.user'),
        ),
    ]
