# Generated by Django 5.1.2 on 2024-12-15 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_projectsmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='users',
            field=models.ManyToManyField(related_name='projects', to='api.user'),
        ),
        migrations.CreateModel(
            name='CouponLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('users_connected', models.ManyToManyField(blank=True, related_name='connected_links', to='api.user')),
            ],
        ),
    ]
