# Generated by Django 5.1.2 on 2024-12-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_couponlink_users_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponlink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='users',
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.comment'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='coupon_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.couponlink'),
        ),
        migrations.AlterField(
            model_name='couponlink',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_links', to='api.user'),
        ),
        migrations.AlterField(
            model_name='couponlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='couponlink',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='couponlink',
            name='users_connected',
            field=models.ManyToManyField(blank=True, related_name='connected_links', to='api.user'),
        ),
        migrations.AlterField(
            model_name='couponlink',
            name='users_connected_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.user'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
