# Generated by Django 5.1.2 on 2024-12-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_comment_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
