# Generated by Django 5.1.2 on 2024-12-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_subscription_created_at_subscription_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='api.projectsmodel'),
        ),
    ]
