# Generated by Django 5.1.2 on 2024-12-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_buyer_delete_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
