# Generated by Django 5.1.2 on 2024-12-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.buyer'),
        ),
    ]
