# Generated by Django 5.1.2 on 2024-12-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_couponlink_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponlink',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_links', to='api.buyer'),
        ),
    ]
