# Generated by Django 5.1.2 on 2024-12-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_couponlink_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='interaction_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
