# Generated by Django 5.1.2 on 2024-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_marker_interaction_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponlink',
            name='link',
            field=models.URLField(max_length=900),
        ),
    ]
