# Generated by Django 5.1.2 on 2025-01-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_couponlink_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
